# do NOT change the config version!
config_version: 1
# set locale for user dialog messages
language: de
# enable debug output
debug: false
# enable safe mode (players will not die from cold. Only for testing!)
safemode: false
# time in seconds to apply the cold damage to players periodically (5-60)
damageApplyPeriod: 10
# base damage per cold damage application when in a cold biome in air
# wether inside or outside (0-20)
baseDamageInAir: 2
# base damage per cold damage application when in a cold biome in water
# wether inside or outside (0-20)
baseDamageInWater: 5
# additional damage for each cold damage application when being outside
# in air (will be added to base damage in air) (0-20)
extraDamageInAirWhenOutside: 2
# additional damage for each cold damage application when being outside
# in water (will be added to base damage in water) (0-20)
extraDamageInWaterWhenOutside: 4
