# do NOT change the config version!
config_version: 1
# set locale for user dialog messages
language: de
# enable debug output
debug: false
# enable safe mode (players will not die from cold. Only for testing!)
safemode: false
# damage per second when outside in a cold biome (0-20)
dps_air: 1
# damage per second when outside and in ice water
dps_water: 3 (0-20)