# do NOT change the config version.
config_version: 1
# set locale for user dialog messages
language: de
# enable debug output
debug: false
# enable safe mode (players will not die from cold. Only for testing.)
safemode: false
# World which will be affected by Arctica (only ONE world possible)
affectedWorld: world
# time in seconds to apply the cold damage to players periodically (5-60)
damageApplyPeriod: 10
# base damage per cold damage application when in a cold biome in air
# wether inside or outside (0-20)
baseDamageInAir: 2
# base damage per cold damage application when in a cold biome in water
# wether inside or outside (0-20)
baseDamageInWater: 5
# additional damage for each cold damage application when being outside
# in air (will be added to base damage in air) (0-20)
extraDamageInAirWhenOutside: 2
# additional damage for each cold damage application when being outside
# in water (will be added to base damage in water) (0-20)
extraDamageInWaterWhenOutside: 4
# burning duration in minutes for flammable materials (1-3600)
# Wool blocks
burnDuration_Wool: 1
# Crafted wood like 'wooden planks' or 'stair' or 'fence' ect.
burnDuration_CraftedWood: 2
# raw wooden logs
burnDuration_Log: 4
# coal ore (farmed with silk touch)
burnDuration_CoalOre: 8
# fuel block consume threshold in percent of burnDuration (50-100)
fuelBlockConsumeThreshold: 80
# jailName (currently only one jail is supported)
jailName: jail
# jail duration (Minimum. (0-60 in minutes) Has to be equal or smaller than maxJailDuration)
# Setting this to 0 will disable jail function
minJailDuration: 1
# jail duration (Maximum. (0-60 in minutes) The used duration depends on the amount of deaths of a player.
# hast to be equal or greater than minJailDuration
maxJailDuration: 5
# A player or mount that dies from cold damage will loose the inventory if set to 'true'.
# No items will be dropped. The inventory will be lost.
clearInventoryOnDeath: false